config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  get "home/about" => "homes#about"

  resources :blogs, only:[:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only:[:create, :destroy]
  end
  resources :users, only:[:index, :show, :edit, :update]
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorites_users, through: :favorites, source: :user

  attachment :image
  
  include JpPrefecture
  jp_prefecture :prefecture_code
  validates :prefecture_code, presence: true
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :correct_user, only:[:edit, :update]

  def show
    @blog = Blog.find(params[:id])
    @user = @blog.user
    @newblog = Blog.new
  end

  def index
    @blogs = Blog.all.sort{ |a, b| b.favorite_users.count <=> a.favorite_users.count }
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blog_path(@blog), notice: "You have created blog successfully."
    else
      @blogs = Blog.all
      render 'index'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blog_path(@blog), notice: "You have updated blog successfully."
    else
      render "edit"
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :body, :image_id)
  end

  

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= render 'layouts/errors', obj: blog %>
<%= form_with model:blog, local:true do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control blog_title' %>
</div>
<div class="form-group">
  <%= f.label :body %>
  <%= f.text_field :body, class: 'form-control blog_body' %>
</div>
<div class="form-group">
  <%= f.attachment_field :image %>
</div>
<div class="form-group">
  <%= f.submit class: 'btn btn-success' %>
</div>
<% end %>

app/views/blogs/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody id="blogs_table">
    <%= render 'blogs/table', blogs: blogs %>
  </tbody>
</table>

app/views/blogs/_table.html.erb
<% blogs.each do |blog| %>
<tr>
  <td>
  <%= link_to user_path(blog.user) do %>
  <%= attachment_image_tag(blog.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
  <% end %>
  </td>
  <td><%= link_to blog.title, blog_path(blog), class: "blog_#{blog.id}" %></td>
  <td><%= blog.body %></td>
  <td id="favorites_btn_<%= blog.id %>">
    <%= render 'favorites/favorite', blog: blog %>
  </td>
</tr>
<% end %>

app/views/blogs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Blog</h1>
      <%= render 'layouts/errors', obj: @blog %>
      <%= render 'form', blog: @blog %>
      <%= link_to 'Show', blog_path(@blog), class: "blog_#{@blog.id}" %> |
      <%= link_to 'Back', blogs_path, class: "back" %>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @blog %>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New blog</h2>
      <%= render 'form', blog: @blog %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Blogs</h2>
      <%= render 'index', blogs: @blogs %>
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/info', user: @blog.user %>
      <h2 class="mt-3">New blog</h2>
      <%= render 'blogs/form', blog: @newblog %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Blog detail</h2>
      <table class="table">
        <tr id="blog_<%= @blog.id %>">
          <td>
            <%= link_to user_path(@blog.user) do %>
            <%= attachment_image_tag(@blog.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @blog.user.name %>
            <% end %>
          </td>
          <td><%= link_to @blog.title, blog_path(@blog) %></td>
          <td><%= @blog.body %></td>
          <td id="favorites_btn_<%= @blog.id %>">
            <%= render 'favorites/favorite', blog: @blog %>
          </td>
          <% if @blog.user == current_user %>
          <td><%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-sm btn-success edit_blog_#{@blog.id}" %></td>
          <td><%= link_to 'Destroy', blog_path(@blog), method: :delete, data: {confirm: '本当に削除しますか？'}, class: "btn btn-sm btn-danger destroy_blog_#{@blog.id}" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>