config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  get "home/about" => "homes#about"

  resources :blogs, only:[:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only:[:create, :destroy]
  end
  resources :users, only:[:index, :show, :edit, :update]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  validates :user_id, presence: true
  validates :blog_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @blog = Blog.find(params[:blog_id])
    favorite = current_user.favorites.new(blog_id: @blog.id)
    favorite.save
    @blogs = Blog.all.sort{ |a, b| b.favorite_users.count <=> a.favorite_users.count }
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    favorite = current_user.favorites.find_by(blog_id: @blog.id)
    favorite.destroy
    @blogs = Blog.all.sort{ |a, b| b.favorite_users.count <=> a.favorite_users.count }
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if blog.favorited_by?(current_user) %>
<%= link_to blog_favorites_path(blog.id), method: :delete, remote: true do %>
♥<%= blog.favorites.count %>
<% end %>
<% else %>
<%= link_to blog_favorites_path(blog.id), method: :post, remote: true do %>
♡<%= blog.favorites.count %>
<% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorites_btn_<%= blog.id %>").html("<%= j(render partial: 'favorites/favorite', locals: {blog: @blog}) %>");
$("#blogs_table").html("<%= j(render partial: 'blogs/table', locals: {blogs: @blogs}) %>");

app/views/favorites/destroy.js.erb
$("#favorites_btn_<%= @blog.id %>").html("<%= j(render partial: 'favorites/favorite', locals: {blog: @blog}) %>");
$("#blogs_table").html("<%= j(render partial: 'blogs/table', locals: {blogs: @blogs}) %>");