config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  root to: 'homes#top'
  get "home/about" => "homes#about"

  resources :blogs, only:[:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only:[:create, :destroy]
  end
  resources :users, only:[:index, :show, :edit, :update]
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class='mx-auto'>
      <p>CopyRight Hatake-Team.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Hatake Team</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li><%= link_to 'Home', user_path(current_user), class: 'nav-link text-light' %></li>
          <li><%= link_to 'Users', users_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'Blogs', blogs_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link text-light' %></li>
          <% else %>
          <li><%= link_to 'Home', root_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'About', home_about_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'Log in', new_user_session_path, class: 'nav-link text-light' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hatake Team</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <p id="notice"><%= notice %></p>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>